### ISSUE TITLE
delays cleanup

### ISSUE THREAD

**Issue by untzag** [wright-group/PyCMDS#101]
- set_zero in base, ini
- set_offset in base, ini
- motor_limits in base, ini
- set_position in base (only set_motor_position in subclass)
- motor units in base, ini
- label in base, ini
- recorded includes all three things...
- document

The hardware-specific code should only contain the following things:
- close
- get motor position
- set motor position
- home
- initialize
- is busy

**Comment by ksunden** [comment]
Is this still ongoing, or is this complete? @untzag

**Comment by untzag** [comment]
Much of it is done, but still some left to do---leave it to me.
