### ISSUE TITLE
spectrometer abstraction

### ISSUE THREAD

**Issue by untzag** [wright-group/PyCMDS#102]
All shared code should be moved into parent class.

**Comment by ksunden** [comment]
Looks like the skeleton is in place, but is not filled to completion

**Comment by untzag** [comment]
Exactly. The MicroHR does more work than it should.

**Comment by ksunden** [comment]
Still the case? @untzag

**Comment by ksunden** [comment]
Closing as these kinds of abstractions are moving to yaqd
