### ISSUE TITLE
record other hardware properties into headers

### ISSUE THREAD

**Issue by untzag** [wright-group/PyCMDS#103]

**Comment by ksunden** [comment]
What sorts of things would this include?

**Comment by untzag** [comment]
This is supposed to remind me to build in a system to allow hardware to record arbitrary key, value pairs in the headers. This will look like a new dictionary, along with `recorded` and `exposed`. The keys would be prepended with the hardware name before writing to ensure uniqueness. It would then be up to the individual hardwares what makes sense to record.

Things in headers should not be scannable.

Examples:
1. mono grating configuration, information
2. OPA shutter configuration
3. PCI-6251 timings

**Comment by ksunden** [comment]
This sounds like a good idea, though perhaps the implementation may look slightly different with the move to HDF5 and reorganization planned on the acquisition side, we will need to discuss in depth when the time arrives
