### ISSUE TITLE
option to cancel out of data processing if scan stopped

### ISSUE THREAD

**Issue by untzag** [wright-group/PyCMDS#109]

**Comment by ksunden** [comment]
See also #138

**Comment by ksunden** [comment]
My personal opinion is that it does not matter if plots/curves are generated, but no side effects should happen (e.g. applying generated curves)

**Comment by untzag** [comment]
@ksunden I agree, but keep in mind that (due to historical bad design) failed processing might also halt the somatic worker thread, which may or may not cause other problems

I think we should try to maintain attempted workup in this case. However, if attempted but failed workup is causing problems I vote we simply move workup under the "if scan complete" switch.

**Comment by untzag** [comment]
as a concrete example, I believe that google drive uploading does not happen if workup fails and raises an exception
