### ISSUE TITLE
Poynting tune load zero curve

### ISSUE THREAD

**Issue by wright-stuff** [wright-group/PyCMDS#126]
Gives a good starting location after aligning from scratch

Not as useful for iterative alignment, though we may decide to make it part of the general procedure

**Comment by untzag** [comment]
In my mind this is premature. Heavy engineering too early freezes bad ideas. Can we wait until we have 4 or 5 good rounds of poynting correction tuning under our belt before returning to this issue?

**Comment by ksunden** [comment]
Closing as it is no longer really even relevant
