### ISSUE TITLE
LTS300 does not report "busy" in GUI when using `set position` in advanced menu.

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/PyCMDS#129]

**Comment by darienmorrow** [comment]
This behavior seems to only exist when sending the stage to `0 mm`. All other positions seems to display `busy` as expected.

**Comment by ksunden** [comment]
Is this related to issue #78?

**Comment by untzag** [comment]
@ksunden nope, unrelated I think

**Comment by ksunden** [comment]
Still an issue?

**Comment by untzag** [comment]
I have no idea
