### ISSUE TITLE
Aerotech stage seems to offer significant delay to PyCMDS smooth shutdown

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/PyCMDS#130]
![image](https://user-images.githubusercontent.com/15792657/29044576-a9db2afc-7b85-11e7-9549-97e515c0cf82.png)

**Comment by ksunden** [comment]
From the error message, looks at first blush to be a timing issue where a command is sent to the stage after it has closed the serial communication (specifically the 'Q' command, which I would think means 'Quit') 

@darienmorrow how important is the 'Q' command, what does it do once it gets to the stage?

**Comment by ksunden** [comment]
After looking at the Aerotek arduino code, I see that 'Q' is actually effectively an 'is_busy' check, (And can also see above that the the message is raised in `is_busy` of the Aerotek stage. 

Can we assume that a closed serial communication is not busy? If so, this is a fairly trivial fix of checking the state of the port before sending the query. 

May be worth adding checks into com_handler itself to prevent sending of communications after the underlying port is closed (at the very least a method to check if it is closed should likely be exposed to the user, who shouldn't interact directly with the underlying serial object)
