### ISSUE TITLE
Allow devices and hardware to be "hot-swappable"

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/PyCMDS#131]
I would _love_ it if certain devices (for instance, the InGaAs array) could be loaded and unloaded into PyCMDS without requiring a restart. 

I assume a massive structural change would be needed in order to make this happen, maybe it is something to think about for PyCMDS's successor...

**Comment by ksunden** [comment]
This is something @untzag and I have discussed as one of the features to build into the successor from the beginning.
