### ISSUE TITLE
Queue acquisition descriptions

### ISSUE THREAD

**Issue by neffmallon** [wright-group/PyCMDS#132]
Currently, the queue only gives you the index, type (aq or wait), status (running, complete, queued), start and end time, and a "DESCRIPTION TODO". Useful things for the description to have would be the acquisition module and scan name, scan info might be helpful as well, but probably isn't necessary.

**Comment by neffmallon** [comment]
pupdate: This may only be a problem with the autotune.

**Comment by ksunden** [comment]
Labeling as fixed, though only Autotune was updated if other modules still need descriptions please open a new issue
