### ISSUE TITLE
data doesn't upload if processing fails

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/PyCMDS#134]
Twice in the last session on the fs table I have done an overnight [w2, w1, d2] movie. Neither time did the `.data` file or `signal` folder of images get uploaded to Google Drive. However, the folders to contain the `.data` file are correctly created with link posted to Slack.

**Comment by ksunden** [comment]
This happens because uploading is at the end of the workup methods, and errors are caught outside of those methods... See #180 for one such example

**Comment by darienmorrow** [comment]
Possibly unrelated: sometimes .pngs get uploaded but .data does not. No useful printout in CLI.
