### ISSUE TITLE
Aerotech communication error(?) during movie

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/PyCMDS#135]
![image](https://user-images.githubusercontent.com/15792657/29241313-ae27b4b2-7f3c-11e7-8ce4-feb2aca7e2d3.png)

**Comment by untzag** [comment]
I'm very sorry to see that :cry: 

Looks like the buffer may have been full, or the timing got off. The status signal ('B' got read by the get position method, which only expects strings that can be converted to floats (as the error suggests).

These kind of rare timing-based events tend to expose themselves only when the motor starts being moved a LOT.

Options are to slow down communication, put buffers in place, or just try except this particular error. I can implement any of these this afternoon @darienmorrow, just let me know.

**Comment by untzag** [comment]
@darienmorrow has this happened since Saturday?

**Comment by darienmorrow** [comment]
@untzag not that I know of.
