### ISSUE TITLE
tuning procedures should not apply curves when acquisition is canceled

### ISSUE THREAD

**Issue by wright-stuff** [wright-group/PyCMDS#138]
Autotune and poynting tune make new tuning curves and upload them automatically even when the tuning scan is halted before completion leading to wild and utterly incorrect curves being loaded. It would be nice if the curves were uploaded only when the tuning scan successfully ran to completion.

**Comment by ksunden** [comment]
Generation may be fine, the real problem is in the application of the generated curve. It can be made/processed, so long as it is not automatically applied when the scan fails or is skipped

**Comment by untzag** [comment]
@ksunden great point
