### ISSUE TITLE
"Current" tab fails to clear when new scan starts

### ISSUE THREAD

**Issue by neffmallon** [wright-group/PyCMDS#14]

**Comment by untzag** [comment]
My assumption is that the module was written incorrectly. It is possible that I wrote it incorrectly, who knows. Do not believe that this is a problem with current tab.

**Comment by neffmallon** [comment]
updates?

**Comment by untzag** [comment]
I believe that mono scan and delay scan both work with the current display. I tore up the 'current tab' in its entirety and moved the display into the DAQ module itself so everything is different now (hopefully better).

For modules to work with the display there are two things to do:
1. Ensure that the x limits of the display are written correctly using `daq.gui.set_slice_xlim(xmin, xmax)`
2. Tell the DAQ each time you are _starting_ a new slice using `daq.control.index_slice(col='d1')`.

This but isn't really useful anymore so I guess I'll close it.
