### ISSUE TITLE
PyCMDS is uploading .png of scan but not .data file. 

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/PyCMDS#147]
See for instance this queue: https://drive.google.com/drive/u/2/folders/1OwN8Ig384tPBVJUSpfeV9sjm2NioSseM

**Comment by darienmorrow** [comment]
Consider [this queue](
https://drive.google.com/drive/folders/1el7lySxZXawUl1T3U7XY_FwwO6dFbtEs). I think `PyCMDS` stopped having proper uploads between acquisitions `005` and `006`. Observe how there aren't the `.aqn` files uploaded after `005`.

**Comment by ksunden** [comment]
Has this remained an issue, is it reproducible?

**Comment by darienmorrow** [comment]
It has not remained an issue.
