### ISSUE TITLE
fs pycmds raises spline error when loading duct-taped `.crv`s

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/PyCMDS#149]
Last experimental session I was able to load `.crv` files which had the signal and idler portions combined. This experimental session, I am not able to due to a spline error. I have attached a screenshot of the error. I was _not_ able to correctly load the `.crv` which worked last session.  Here are the curves which don't load properly: [OPA2 (10742) curves.zip](https://github.com/wright-group/PyCMDS/files/1523423/OPA2.10742.curves.zip)

I suspect this has something to do with us having updated the packages on the fs computer.
![image](https://user-images.githubusercontent.com/15792657/33509677-3e3f6ba6-d6c9-11e7-97ce-f477aef2fe1a.png)

**Comment by untzag** [comment]
@darienmorrow your screenshot has been scaled down and I cannot read the specific error

**Comment by p770193** [comment]
![spline error](https://user-images.githubusercontent.com/11864045/33582532-4f5109aa-d91b-11e7-94dd-abc5998bd36f.png)

**Comment by darienmorrow** [comment]
@p770193 Thanks!!!

**Comment by ksunden** [comment]
I believe this to be fixed by above WrightTools PR. Please reopen if this is not the case
