### ISSUE TITLE
PyCMDS pseudo crash

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/PyCMDS#156]
I came in this morning and looked at the ps computer.
1) the computer was locked, I don't think this is intended behavior. @ksunden @jhandali ?
2) 2 scans had failed in PyCMDS.
3) I scan was stuck with both OPAs busy. I attach a screen shot of the command line.
4) The ps computer has no network access.

![2018-03-27 psuedo crash](https://user-images.githubusercontent.com/15792657/37969400-42694a1c-3196-11e8-87c5-3b76d9e31878.png)

**Comment by ksunden** [comment]
Restart of the machine saw these errors go away.

We should think a bit about handling the case where internet goes down (I think gdrive may have some protections in place, but slack does not)

Closing as not reproducible, will reopen if we see this again
