### ISSUE TITLE
PS PyCMDS startup failure

### ISSUE THREAD

**Issue by jhandali** [wright-group/PyCMDS#157]
OPA 2 and OPA 3 "busy" right after starting up.
![180330_startupfailure](https://user-images.githubusercontent.com/13207251/38145989-c8cac790-3400-11e8-98f0-52240c2f5eda.PNG)

**Comment by jhandali** [comment]
After restarting PyCMDS, things were back to normal.

**Comment by ksunden** [comment]
This issue is stochastic, but has been happening often lately

**Comment by ksunden** [comment]
This appears to be due to a race condition in the initialization of hardware.

Not yet sure why the race condition occurs, as the flag is a that `Hardware object has no attribute destination`, though the attribute is set in `__init__`

**Comment by ksunden** [comment]
Closing as we have not seen this lately
