### ISSUE TITLE
plotting of ND wheel axis does not have expected output

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/PyCMDS#166]
![image](https://user-images.githubusercontent.com/15792657/39127325-54a6e376-46ca-11e8-9c67-83e32d745255.png)
The above should show a scan from 0 to 200 degrees, but instead only shows the first ~20 and also shows negative values which were not scanned.

**Comment by darienmorrow** [comment]
oh, the labels for the ND wheels are both `0` and not indexed correctly, too.

**Comment by ksunden** [comment]
Looks to me like it's plotting motor position in absolute, rather than corrected for zero position/factor
