### ISSUE TITLE
Simultaneous homing of MFA delays seems to cause communication problem where one or both delays hang forever

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/PyCMDS#168]
@ksunden has definite thoughts on the matter. Please fill in.

**Comment by ksunden** [comment]
There seems to be some cross talk where the two delay stages (which communicate on the same serial port) are reading each other's communications. I think, it's hard to see how that would occur given the code.... Would need to see what each is trying to parse when it fails.

**Comment by ksunden** [comment]
I believe this is addressed by yaqd-newport (though have only had one, so have not tested)
