### ISSUE TITLE
filters.ini is incorrectly written to. All entries get listified and stringified 

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/PyCMDS#176]
This has happened once (twice?) before. At the time, @ksunden and I couldn't figure out why. 

```
[nd0]
enable = ['False']
model = ["'Homebuilt'"]
native_units = ["'deg'"]
display_units = ["'deg'"]
label = ["''"]
position = ['200.7']
motor_position = ['-213.3']
path = ["'C:/Users/John/Desktop/PyCMDS/hardware/filters/homebuilt/homebuilt.py'"]
serial = ["'blah'"]
motor_units = ["'steps'"]
zero_position = ['-12.6']
index = ['0']
factor = ['-1']
serial_port = ['18']
full_steps_per_rotation = ['400']
degree_of_microstepping = ['1', '']

[nd1]
enable = ['True']
model = ["'Homebuilt'"]
native_units = ["'deg'"]
display_units = 'deg'
label = ''
position = 39.6
motor_position = -21.6
path = ["'C:/Users/John/Desktop/PyCMDS/hardware/filters/homebuilt/homebuilt.py'"]
serial = ["'blah'"]
motor_units = ["'steps'"]
zero_position = 18.0
index = ['1']
factor = -1
serial_port = ['18']
full_steps_per_rotation = ['400']
degree_of_microstepping = ['1', '']

[nd2]
enable = ['True']
model = ["'Homebuilt'"]
native_units = ["'deg'"]
display_units = 'deg'
label = ''
position = 10.8
motor_position = 7.2
path = ["'C:/Users/John/Desktop/PyCMDS/hardware/filters/homebuilt/homebuilt.py'"]
serial = ["'blah'"]
motor_units = ["'steps'"]
zero_position = 18.0
index = ['2']
factor = -1
serial_port = ['18']
full_steps_per_rotation = ['400']
degree_of_microstepping = ['1', '']
```

**Comment by DLafayetteII** [comment]
The bug emerged after the following series of events:
-Homed all delays
-Added a scan to queue before delays had finished homing
-interrupted queue soon after appending after realizing that delays had not finished homing.
-PyCMDS stopped responding
-Opted to close PyCMDS after waiting ~30 seconds

PyCMDS was unable to start up again due to the issue above.

**Comment by ksunden** [comment]
I've seen this before, but was never able to reproduce it.
Tedious, but deleting the list/string markers allows you to run again

**Comment by ksunden** [comment]
It has happened at least twice before, though one of them was when I was actively changing filter stuff, so I didn't think much of it.

**Comment by ksunden** [comment]
I have not seen it on any other machine, though we have not extensively used the filter wheels on other machines.

**Comment by darienmorrow** [comment]
Triggered again. Graceful shutdown. Restarted next day and got the standard `TypeError: expected str, bytes or os.PathLike object, not list`.

**Comment by darienmorrow** [comment]
Something interesting to note is that not all enteries are written over incorrectly, for instance `display_units` is _not_ written over while `native_units` is... 
```
[nd2]
enable = ['True']
model = ["'Homebuilt'"]
native_units = ["'deg'"]
display_units = 'deg'
label = '2'
position = -3.55271368e-15
motor_position = 25.2
path = ["'C:/Users/John/Desktop/PyCMDS/hardware/filters/homebuilt/homebuilt.py'"]
serial = ["'blah'"]
motor_units = ["'steps'"]
zero_position = 25.2
index = ['2']
factor = -1
serial_port = ['18']
full_steps_per_rotation = ['400']
degree_of_microstepping = ['1']
ng = ['1', '']
```

**Comment by ksunden** [comment]
Possibly can simulate with only an arduino, though we also have at least one  spare box

**Comment by p770193** [comment]
Triggered again upon startup 2018.10.12

**Comment by darienmorrow** [comment]
Triggered again 2019-11-11 by @DLafayetteII

**Comment by untzag** [comment]
this ini file was removed by refactor---we can reopen this issue later but all reason would suggest that it must have been fixed
