### ISSUE TITLE
No bounds on ND filter positions

### ISSUE THREAD

**Issue by DLafayetteII** [wright-group/PyCMDS#177]
PyCMDS accepts any value of degree position.  I recently entered 110 in front of 100, resulting in a ~5 minute wait while the ND wheel spun 110100 degrees. If it takes less than 5 minutes to bound the accepted values, probably worth patching. 

I somewhat arbitrarily suggest +-4pi since I could envision a situation in which +-2pi is overly constraining.

**Comment by neffmallon** [comment]
It seems like better would be to take the requested value (in radians) and then mod 2 pi and then compare that to the position it is already, then tell it to move the appropriate amount in the correct direction, yeah? This way any angle is acceptable, it updates its angle when it gets to the correct spot, and uses the shortest path to get to its goal?

**Comment by ksunden** [comment]
Implemented in the yaq daemon
