### ISSUE TITLE
Queue:  scans still runs after queue is stopped

### ISSUE THREAD

**Issue by ddkohler** [wright-group/PyCMDS#190]
Ran an autotune with multiple scans and tried to interrupt by stopping the queue.  Instead it went to the next scan, even though the queue reported that it was stopped.

**Comment by untzag** [comment]
I believe this problem is limited to autotune

**Comment by ksunden** [comment]
I'm interested in testing this out with some of the changes to the queue that are nearing merging, though I don't think behavior has changed in this respect

**Comment by ksunden** [comment]
Relates to #138
