### ISSUE TITLE
Load functionality in queue does not work on fs computer

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/PyCMDS#198]
Console error message upon clicking `load`:
![image](https://user-images.githubusercontent.com/15792657/49345021-c51cad00-f644-11e8-850e-4d9ad87d8585.png)

**Comment by darienmorrow** [comment]
Note, I am not attempting to "load from file" but rather load an acquisition that has already been run in the current queue.

**Comment by ksunden** [comment]
Ahh, I think I have an idea, but will have to look a little closer to be sure

**Comment by ksunden** [comment]
I think it has something to do with the fact that files are renamed after they are run, though if you are selecting the file, it should exist... need to think on it a bit more

**Comment by darienmorrow** [comment]
Loading seems to be broken in a weirder way than initially thought. 

If the current append to queue `type` is `hardware` then I can load an `acquisition`. If the current type is `acquisition` I can load a `hardware`. However, no matter what acquisition I choose to load, only the last acquisition in the queue gets loaded.
