### ISSUE TITLE
revamp internal curve handling 

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/PyCMDS#239]
- [ ] remember past curves which have been applied since PyCMDS startup
- [ ] option to revert to previous curve
- [ ] require internal folder structure for a hardware's curve. Curves will _always_ be copied into this folder before being applied.
- [ ] no autogeneration of OPA1/OPA2 TOPAS-C folders

**Comment by darienmorrow** [comment]
Internal folder structure should also be implemented for what used to be called cosets.

**Comment by ksunden** [comment]
Implemented in attune directly
