### ISSUE TITLE
Process motortune tuning curves need more decimal places

### ISSUE THREAD

**Issue by jhandali** [wright-group/PyCMDS#33]
Now that the mixing crystal is the most sensitive motor, we need to extend the accuracy of the positions generated by the process motortune module. Could we have the grating and bbo tuning points to be up to 3 decimal places and the mixer tuning points up to six?

**Comment by untzag** [comment]
This should be doable. Could you upload a representative motortune and its corresponding tuning curve for me to work with?

**Comment by jhandali** [comment]
I've attached one here. I had to save it as a txt file for github to accept.
[OPA3_forBlaise.txt](https://github.com/wright-group/PyCMDS/files/65168/OPA3_forBlaise.txt)

**Comment by untzag** [comment]
OK @jhandali I think the push I just made to WrightTools master _should_ fix the problem. I will mention that I've also changed around how curve objects work generally so you may see other changes / problems. Just let me know.
