### ISSUE TITLE
Tune curve generator has insufficient decimal places

### ISSUE THREAD

**Issue by jhandali** [wright-group/PyCMDS#36]
The tune curve generator only defines positions up to 2 decimal places. DFG actuator for w1 (and perhaps w3 but I haven't tried it yet) requires up to 4 decimal places to be defined to a proper level of precision.

**Comment by untzag** [comment]
Are you using an old version of WrightTools? In the current master I write [5 decimals](https://github.com/wright-group/WrightTools/blob/master/tuning/curve.py#L583).

Let me know if I'm wrong. Should be a quick fix.
