### ISSUE TITLE
NI 6251 - simultaneous analog input and analog output

### ISSUE THREAD

**Issue by untzag** [wright-group/PyCMDS#38]
Historically, I've heard that the card takes a 'very long time' to switch between input and output mode, but [further reading](http://forums.ni.com/t5/Multifunction-DAQ/simultaneous-analog-input-and-analog-output/td-p/462554) makes me think that it may be possible to allocate physical channels / samples to output without sacrificing our wonderful input parameterization. This would be powerful for obvious reasons, although as a rule I still prefer scan hardware to run separately if possible (things like Arduino make that possible over usb for homebrew hardware).

I'm opening this issue to serve as a placeholder / location to discuss how we might use analog output features from our 6251 cards. I have no plans to add this functionality in the near future.

**Comment by neffmallon** [comment]
This is a beautiful idea that could allow us to more easily create multi-triggered sample and hold devices for our pyros etc. I agree that developing this is should not be a priority for you, but if you could compile the sources from which you have gleaned this information here, that would be wonderful.

**Comment by ksunden** [comment]
May be abstractable without hardware now, but since it is phrased as NI specific, adding the tag

**Comment by ksunden** [comment]
Closing as all NI daq code was exported by #291
