### ISSUE TITLE
recover 'save shots' functionality

### ISSUE THREAD

**Issue by untzag** [wright-group/PyCMDS#39]
I broke 'save shots' when overhauling the DAQ, and didn't fix it because I didn't consider it a priority at this time. The infrastructure is there in parts, it should only take my dedicated attention for a day or two to bring it back.

**Comment by untzag** [comment]
Probably save shots functionality should be unique to each device... so NI 6251 would save its own shots etc.

**Comment by ksunden** [comment]
Closing as all daq functionality is now external #291
