### ISSUE TITLE
google drive upload memory overflow

### ISSUE THREAD

**Issue by untzag** [wright-group/PyCMDS#41]
I've been working on tuning procedures using the InSb array detector, which can easily generate .data files upwards of 100 MB. When these files are sent to the google drive handler, a `MemoryError` is raised inside of google drive because the file is too large to load entirely into the python allocated memory (my naive understanding). What we _want_ to happen is for the file to be uploaded in pieces, something google drive is certainly capable of but isn't doing for us.

In searching to understand this problem, I found [this issue](https://github.com/googledrive/PyDrive/issues/55) open in the PyDrive repository. The reported error is identical to the one we experience. Amazingly, it seems like we might be running up against a bug in PyDrive itself.

Based on the comment in the above issue by Fjodor42, I 'hacked' the `http.py` module in `googleapiclient` on the fs computer. All I did was change the default of the kwarg `resumable` (line 285) to `True` (it was originally `False`). **This has fixed the `MemoryError` problem.** I don't fully understand why. 

I'd strongly prefer not to have to edit `googleapiclient` itself in the long run. People [here](https://github.com/googledrive/PyDrive/issues/27) talk about fixing the issue by using the api client directly - bypassing PyDrive. Perhaps this is something we could do in the future.

**Comment by darienmorrow** [comment]
@untzag, is a memory cap in place for every launched thread in PyCMDS? In other words, does PyCMDS impose restrictions on how much memory our Google Drive method can use?  I ask this because as demonstrated yesterday, our method is perfectly capable of uploading "large" files (~750mb) without generating a memory error. 

Also, does this error happen after uploading many other files before the 100mb file that throws up the error? In other words, is the Google Drive method attempting to keep all uploaded items in memory?

**Comment by untzag** [comment]
It doesn't have anything to do with multiple files not being cleared from memory I'm pretty sure. The error occurs even on the first file uploaded after a clean startup.

As far as I know there is no memory cap on a thread-by-thread basis in PyQT. However the entirety of PyCMDS must obey the [GIL](https://wiki.python.org/moin/GlobalInterpreterLock) so all of the other pieces of PyCMDS have to share memory with PyDrive.

My suspicion is that one of the following is true:

1. PyCMDS doesn't have enough additional memory to represent the files
2. Your test case with ~750 MB doesn't exactly replicate PyCMDS' implementation in some small way that changes this behavior
3. PyDrive treats uploading video files differently than data files. Perhaps the developers made a special case for video files since they anticipated them as large.

Unfortunately I think the only way to understand how this black box works is to poke at it a bit with some 'experimental programming'. At your earliest convenience could you attempt to upload [this folder](https://drive.google.com/folderview?id=0B5XBhboKMJCTbWFQejNOU1MzLXc&tid=0B5XBhboKMJCTeFhpc0FRNlZ6Wlk) using your script?

For now we have a workaround, so I'm content :neutral_face:.

**Comment by darienmorrow** [comment]
Folder upload works perfectly.

**Comment by untzag** [comment]
Well that tells us something. Could you look through the google drive implementations on your machine and in PyCMDS to see if any differences pop out at you? The fs branch is most current at the moment.

**Comment by neffmallon** [comment]
The issue referenced in the first post here has been closed and fixed. I'll let you know if we still see the error.
