### ISSUE TITLE
Stopping a Scan before any points aquire

### ISSUE THREAD

**Issue by jhandali** [wright-group/PyCMDS#42]
If you stop a scan before you acquire any points, you get an error in scan.py when making the data object because of an invalid index to scalar variable. This is probably because there are no data points, so it makes problems.

Anyway, the "Please wait" window never goes away, even when you shut down the program. The other threads appear to shut down, but I'm not sure. They all dequeue close and check_busy. However, when I kill the window, there are 4 threads that are destroyed while still running.

-- by Nathan

**Comment by untzag** [comment]
I see. I guess I need an additional sanity check of some type when attempting to import the data.

**Comment by untzag** [comment]
The somatic system has changed so dramatically that this is no longer relevant.
