### ISSUE TITLE
Create Additional interpolation methods for tuning curves

### ISSUE THREAD

**Issue by neffmallon** [wright-group/PyCMDS#48]
Polynomials are great, but don't necessarily do a good job covering DFG over a very wide range. In addition, because of weird interference effects, it looks like the DFG mixer curve might not be as smooth as a polynomial. Consider splines, linear interpolation, etc.

**Comment by untzag** [comment]
There is already a [linear interpolation method](https://github.com/wright-group/WrightTools/blob/1a0802f75fa5fcffbe94c784f4d72b4724ec30a8/tuning/curve.py#L56).

A spline interpolator is a good idea and not hard to do. I just created a working version - it will be in the master soon.
