### ISSUE TITLE
Coset file ini string problems

### ISSUE THREAD

**Issue by neffmallon** [wright-group/PyCMDS#49]
When a new coset file is set, the string is often written to the ini file without quote marks, like so:

`opa3 micro = C:\Users\John\Desktop\PyCMDS\coset\files\d1_w3_cob_2-62A.coset`

However, when the program tries to read the ini and the file name is too long, it will chop off the last few characters and PyCMDS will crash... UNLESS there are quote marks around the file name like so:

`opa3 micro = 'C:\Users\John\Desktop\PyCMDS\coset\files\d1_w3_cob_2-62A.coset'`

**Comment by untzag** [comment]
Done
