### ISSUE TITLE
PyCMDS needs to be restarted when loading new shot processing module

### ISSUE THREAD

**Issue by jhandali** [wright-group/PyCMDS#53]
Is there a way the shot processing module and all its relevant settings could be automatically loaded without restarting PyCMDS?

**Comment by untzag** [comment]
@jhandali I believe this is an easy workaround. I have just forgotten to force the update when the filepath changes. To force an update, try placing your cursor in the shots control and hitting tab to make PyCMDS think that you may have updated the number of shots.
