### ISSUE TITLE
Witch handling capitals

### ISSUE THREAD

**Issue by neffmallon** [wright-group/PyCMDS#57]
Witch should handle capital letters (i.e. 'Status' and 'status' should work the same). And she should remind people not to yell if they use all caps.

**Comment by untzag** [comment]
This is easy, I can do it next time I sit down with PyCMDS.

As a reminder to future me: just add `str.lower()` call in pipeline between reading from slack and interpreting.

**Comment by neffmallon** [comment]
and if `text == str.lower()` too, just for fun.

**Comment by untzag** [comment]
done in next version
