### ISSUE TITLE
migrate to python 3

### ISSUE THREAD

**Issue by untzag** [wright-group/PyCMDS#68]

**Comment by ksunden** [comment]
Are there any parts that are not currently python 3 compatible? I know we are fully python2 compatible, and that the core interface is python 3 compatible, but are there known issues with any other parts?

**Comment by untzag** [comment]
I just don't know about the hardware libraries.

@ksunden if you agree, I move that we close this issue and call the package python 3 ready

The hardware libraries can be addressed on a case-by-case basis.

**Comment by ksunden** [comment]
I agree, new issues should be created if there are any python2 specific code in particular portions
