### ISSUE TITLE
PyCMDS crashing with long scans

### ISSUE THREAD

**Issue by jhandali** [wright-group/PyCMDS#71]
PyCMDS crashes when doing long (multidimensional, I haven't yet tried to do very very long 1d scans) scans. The program does not technically crash but just decides at one point in the scan to stop moving. No error reported. In the instances that I have seen, the freezing occurred in the middle of a slice and not during a carriage return. I have twice seen the program freeze around 50 minutes into the scan, and once 14 minutes into the scan. In both cases, OPA1 motors were the scanning motors.

It's basically impossible to do any serious scanning. I'm checking to see if the same thing occurs when OPA2 or the TOPAS is the scanning OPA.

**Comment by untzag** [comment]
Gosh, that sounds terrible... I don't really have the information or time to diagnose this right now. Please keep me tuned.

**Comment by jhandali** [comment]
Ya, will do. I've done some tests and can tell you more tomorrow. We can address it when you are available.

**Comment by untzag** [comment]
I think that I've fixed this. I've managed to do a full 51x51 2D frequency scan (with spectral delay correction) without issue. Try it out and let me know if you experience any further problems.

I'm not sure if what I've done has negatively affected scan speed - let me know about that.

**Comment by ksunden** [comment]
@jhandali Is this issue still relevant?

**Comment by ksunden** [comment]
I have not heard anything on this issue lately, and long scans have been run on both systems. Closing
