### ISSUE TITLE
Tuning curve processing scripts no longer working

### ISSUE THREAD

**Issue by jhandali** [wright-group/PyCMDS#72]
Curve.save no longer works in the process_tunetest module. When I try to run the script I get this error:
  File "C:\Python27\lib\site-packages\numpy\lib\npyio.py", line 1014, in savetxt 
    fh = open(fname, 'w') 

IOError: [Errno 22] invalid mode ('w') or filename: u'C:\Users\John\Desktop\PyCMDS\data\TUNE TEST [w1, wm] 2016-09-07 66054\OPA1 - 2016-09-08T12:05:11-05:00.curve'

Also, there appears to be a problem with the WrightTools/Data Collapse function. It is deeply involved in one of Nathan's tuning curve fitting scripts and when I run it I get this error:

File "C:/Users/John/Documents/MyScripts/tune_workup.py", line 78, in <module> 
    outs = fitter.run(channel = c_n) 

  File "WrightTools\fit.py", line 415, in run 
    self.outs.collapse(a, method='integrate') 

  File "WrightTools\data.py", line 544, in collapse 
    for method, channel in zip(methods, self.channels): 

UnboundLocalError: local variable 'methods' referenced before assignment

**Comment by untzag** [comment]
Thanks for the specific error reporting, @jhandali, that really helped me track stuff down. :kissing_heart:

I _think_ that I have understood and fixed both of these problems. Please try for yourself and let me know if everything is working. If it is, I'll commit the changes I've made.

Sorry for the 'rough landing' on this one...

**Comment by jhandali** [comment]
@untzag Process tune-test is working again! 
However there seems to be another problem now with calling the data file of a 3d scan (2d motortune at each tune point). When I do data = wt.data.from_PyCMDS(file_path), I get the error message:

  File "C:/Users/John/Documents/MyScripts/manual_workup.py", line 16, in <module>
    data = wt.data.from_PyCMDS(file_path)

  File "C:\Users\John\Documents\MyScripts\WrightTools\data.py", line 2239, in from_PyCMDS
    points -= centers

ValueError: operands could not be broadcast together with shapes (9,49,9) (441,) (9,49,9)
