### ISSUE TITLE
add interrupt capabilities to queue

### ISSUE THREAD

**Issue by untzag** [wright-group/PyCMDS#73]
Name and info given by user should show up in pop-up window when interrupt occurs.

Message on slack 'queue interrupted' or similar.

**Comment by untzag** [comment]
perhaps there should be some option to interrupt the queue after a certain amount of time has elapsed (to account for dewar refills etc)

**Comment by ksunden** [comment]
Closing because this functionality exists. If you wish to extend the functionality as indicated in the comment, please file a new issue specific to that extension
