### ISSUE TITLE
NI 6251 shots-level quality of life changes

### ISSUE THREAD

**Issue by untzag** [wright-group/PyCMDS#77]
- big number / selection combobox to see processed value
- x (shot index) range update
- new shots processing script is immediately used

**Comment by untzag** [comment]
fixed: loading new shots processing script now forces task to update

**Comment by ksunden** [comment]
May be abstractable without hardware now, but since it is phrased as NI specific, adding the tag

**Comment by ksunden** [comment]
Closing as all daq behavior is now external
