### ISSUE TITLE
LTS300 backlash

### ISSUE THREAD

**Issue by untzag** [wright-group/PyCMDS#78]
I have observed that the LTS300 occasionally gets caught in a 'forever busy state'. For some reason, the `isMotorMoving` responds `False` for just a moment _during motor motion_.

I believe that this is due to some unexpected behavior in the LTS300 driver w.r.t. backlash correction. The driver might respond `False` during the time after the motor has moved to its backlash location, and before its started motion to its final destination.

For now have hacked my way around this problem by having an 'are you sure' loop following the 'are you done' loop. There is a 10 ms wait between the loops, to ensure that they don't both get caught in the turnaround window. 1 ms wait is too small but 10 seems to never fail.

I believe that I should disallow driver-level backlash correction, and implement backlash in my own hardware code. By doing this I could get rid of the unnecessary wait slop and ensure that I never get caught forever as `BUSY`.

**Comment by ksunden** [comment]
@untzag Is this still an issue after the LTS300 rewrite you did since this issue was posted

**Comment by untzag** [comment]
probably---I should look into it

leave it for now

**Comment by ksunden** [comment]
Do not believe this is still an issue, reopen if it presents itself again
