### ISSUE TITLE
create picosecond delay module

### ISSUE THREAD

**Issue by untzag** [wright-group/PyCMDS#8]

**Comment by neffmallon** [comment]
I've created a new controller/motor structure. Still needs to be tested.

**Comment by neffmallon** [comment]
I believe delays have been tested and are working. I'm proposing we close this issue.

**Comment by untzag** [comment]
Still a whole lot to be done. You can't even give the delays a zero position through the software.

**Comment by neffmallon** [comment]
Is this a good summary of the remaining tasks? Finish simple GUI, create and design advanced GUI/functions

Anything else?

**Comment by neffmallon** [comment]
I'm marking this as closed. I'm happy with what we have.
