### ISSUE TITLE
loosen dependency on pyvisa

### ISSUE THREAD

**Issue by untzag** [wright-group/PyCMDS#82]
Currently PyCMDS handles com support through the [PyVISA](https://pyvisa.readthedocs.io/en/stable/) library. The PyVISA library is OK, although I'm not pleased with the de-facto dependence on national instruments VISA.

Currently, the [com_handler](https://github.com/wright-group/PyCMDS/blob/master/project/com_handler.py) imports PyVISA upon import. In the interest of portability, I would like to ensure that the serial communication library, whatever it is, is only imported when PyCMDS actually requires communication with such hardware. PyCMDS should start up without complaint on a machine without PyVISA.

**Comment by ksunden** [comment]
Switched to pyserial
