### ISSUE TITLE
better naming conventions

### ISSUE THREAD

**Issue by untzag** [wright-group/PyCMDS#86]
I'm open to the idea of changing around naming conventions within the program as we move it from "minimum viable" to "stable".

Here are the current ideas.

**PROGRAM ITSELF**
- SpecPy
- spectroscoPy

**PROGRAM COMPONENTS**
- hardware → machines
- devices → instruments
- OPAS → sources (would be a conceptual shift---widen scope to all adjustable light sources)

Thoughts?

**Comment by ksunden** [comment]
Closing as out of scope for PyCMDS
