### ISSUE TITLE
Loading previous scan Constants

### ISSUE THREAD

**Issue by jhandali** [wright-group/PyCMDS#89]
Loading a previous scan loads the constants from that scan, but does not show them in the GUI.

Attempting to add the constant back via the gui results in a duplicate constant error.

**Comment by jhandali** [comment]
Seems that the issue persists to new scans, even new queue (not loading a scan any more)

Not clearing constants properly

**Comment by jhandali** [comment]
Workaround: click 'REMOVE' on the constants to remove all constants, then click again to remove the one that doesn't show up

**Comment by jhandali** [comment]
This bug was described in the comments of #58 by @darienmorrow

**Comment by untzag** [comment]
Fixed
