### ISSUE TITLE
OPAs can be sent out of their range by the scanning feature

### ISSUE THREAD

**Issue by jhandali** [wright-group/PyCMDS#92]

**Comment by untzag** [comment]
@jhandali I'm not sure what you mean by this. Can you say more?

**Comment by jhandali** [comment]
Ya, sorry for being unclear. I set up a scan and picked the wrong w on the energy axis. I set the range from 4000 wn to 1000 wn, but accidentally picked w2 instead of wm. 4000 wn is beyond the limit of w2 but the program did not realise it and tried to send it to the new frequency.

**Comment by jhandali** [comment]
After which chaos ensued.

**Comment by untzag** [comment]
this is intended behavior
