### ISSUE TITLE
Monochromator limit on the front panel at 20,000 wn

### ISSUE THREAD

**Issue by jhandali** [wright-group/PyCMDS#93]
The monochromator will only report its frequency as high as 20,000 wn on the front panel. When I set it to 20,500 wn, the grating actually goes to that position, but the front panel reports 20,000 wn. At any frequency below 20,000 wn, it operates normally.

**Comment by untzag** [comment]
Fixed by https://github.com/wright-group/PyCMDS/commit/29afc7a7ad7f5cec9f6cb5f94b6fefc938cd7a1c.
