### ISSUE TITLE
Save Shots broken

### ISSUE THREAD

**Issue by neffmallon** [wright-group/PyCMDS#95]
I tried to save shots this morning and HDF5-DIAG was unable to open the .hdf5 files to save the shots. Here is the error message. PyCMDS did not crash, but it did not save shots.
![start queue error message 20170419](https://cloud.githubusercontent.com/assets/13207223/25190011/974de082-24f0-11e7-93f8-6abed1b35492.png)

**Comment by untzag** [comment]
Are you sure shots were not saved? I think this error is cosmetic---it looks scary, but the file is still written.
