### ISSUE TITLE
TOPAS-800 motor homing does not match WinTOPAS procedure

### ISSUE THREAD

**Issue by untzag** [wright-group/PyCMDS#96]
Light conversion does not offer a simple home motor function in their driver, so we have to hack together our own function from lower-level operations like "read reference switch" and "move relative". Our procedure was written to mimic the WinTOPAS homing procedure on the fs system with the TOPAS-C OPAs.

1. Send motor to left reference switch at default speed
2. Back off of switch by 400 steps at default speed
3. Send motor to reference switch at half speed
4. Back off of switch by 400 steps at half speed
5. Current motor position is now zero steps
6. Return to desired position at default speed

Any change to this procedure was found to cause disagreement between WinTOPAS and PyCMDS. Full compatibility with WinTOPAS is an important feature---I'd really like to maintain it.

Unfortunately it seems like the above procedure does not mimic WinTOPAS for the TOPAS-800 on the ps system. I'm not sure if this is due to a change in WinTOPAS or a difference in the OPA design.

Skye contacted Light Conversion to get the procedure above---we probably need to do that again to see what is different with the new OPA.

For now, do not home the TOPAS motors on the ps system.

**Comment by ksunden** [comment]
The WinTOPAS 4 API exposes the home command directly, but it's ambiguous if the TOPAS-C's will be able to communicate via that API, and would require some amount of rewriting

**Comment by ksunden** [comment]
Closing as we now use topas4 via a daemon (#258)
